server:
  port: 8005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a8897766/springcloud-config.git
          username: a8897766
          password: ZCBxvn123





